model_name: '231030'

# training setting
epochs: 500
batch_size: 16
lr: 0.0005
num_workers: 8

# I/O
# Input
folder: '/root/VGHTC/No_IV_197_preprocessed'
list_path: '/root/VGHTC/CTSegment/data/trainList.txt'
val_list_path: '/root/VGHTC/CTSegment/data/testList.txt'
test_list_path: '/root/VGHTC/CTSegment/data/testList.txt'
json_path: '/root/VGHTC/CTSegment/data/label.json'
# Output
show_num: 4

# model setting
num_classes: 72
resolution: 512
down_times: 5

# data setting
default_orient: 'LAS'